version: '3'

services:
  web:
    ports:
      - 3000:3000
      - 9229:9229
    expose:
      - 9229
    command: ./node_modules/.bin/nodemon --inspect=0.0.0.0:9229 --ext js,graphql,json -L /usr/src/app/index.js index.js